import React, { Component } from 'react';
import Index from './home'
import './App.css';

class App extends Component {
  render() {
    let navList = [
        {
            "hostname": "http://192.168.145.155:9090/ndssboot-web",
            "checkedIcon": "http://192.168.145.34/group2/M00/00/AD/wKibNVpf_6HZrqj-AAACHzonx_8575.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group2/M00/00/AD/wKibNVpf_6HrB43OAAACHzonx_8790.png",
            "icon": "",
            "name": "规则引擎_风控",
            "parentIds": "",
            "pId": "0",
            "id": "10248",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "规则配置管理",
            "parentIds": "0/",
            "pId": "10248",
            "id": "3465",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.155:9090/ndssboot-web/pages/sysandrule/systemList.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "决策流配置",
            "parentIds": "0/3465/",
            "pId": "3465",
            "id": "3467",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.155:9090/ndssboot-web/pages/publicRuleLib/publicRuleList.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "公共规则配置",
            "parentIds": "0/3465/",
            "pId": "3465",
            "id": "3466",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.155:9090/ndssboot-web/pages/dataIntegration/dataIntegration.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "数据集管理",
            "parentIds": "0/",
            "pId": "10248",
            "id": "2515",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5QHrsYL2AAAAEfbEZwcI560.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5QHrEMISVAAAEeGxFFc4037.png",
            "icon": "oa",
            "name": "易鑫OA",
            "parentIds": "",
            "pId": "0",
            "id": "10004",
            "target": "_blank"
        },
        {
            "hostname": "http://124.250.36.150:808/login.aspx",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "我的考勤",
            "parentIds": "0/",
            "pId": "10004",
            "id": "266",
            "target": "_blank"
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RZ3Eu6vlAAAEf5L2RMY298.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RZ2_kKIwAAAEcqmpUMc465.png",
            "icon": "erpxt",
            "name": "ERP系统",
            "parentIds": "",
            "pId": "0",
            "id": "10011",
            "target": "_blank"
        },
        {
            "hostname": "http://erpdev.yxin.com:8023/OA_HTML/SSOServlet",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "ERP系统",
            "parentIds": "0/",
            "pId": "10011",
            "id": "313",
            "target": "_blank"
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5QMzu3ubzAAAEQ2cDCYc286.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5QMzQVbBwAAAEI0kdD1o499.png",
            "icon": "alix",
            "name": "融资租赁系统(Alix)",
            "parentIds": "",
            "pId": "0",
            "id": "10041",
            "target": "_blank"
        },
        {
            "hostname": "http://alix.yiche.com/login/index.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "融资租赁系统(Alix)",
            "parentIds": "0/",
            "pId": "10041",
            "id": "1357",
            "target": "_blank"
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RVf3_fetAAAEM80bmik744.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RVf85oVRAAAELpFSy9Q430.png",
            "icon": "ityw",
            "name": "IT运维",
            "parentIds": "",
            "pId": "0",
            "id": "10012",
            "target": "_blank"
        },
        {
            "hostname": "http://zck.yccdn.com/",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "IT支持库",
            "parentIds": "0/",
            "pId": "10012",
            "id": "316",
            "target": "_blank"
        },
        {
            "hostname": "http://itoms.bitautotech.com/",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "IT运维平台",
            "parentIds": "0/",
            "pId": "10012",
            "id": "314",
            "target": "_blank"
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RYKPUBwJAAAD--ii9ng836.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RYKmPVbPAAAD4-BWpMA778.png",
            "icon": "sldp",
            "name": "商旅订票",
            "parentIds": "",
            "pId": "0",
            "id": "10013",
            "target": "_blank"
        },
        {
            "hostname": "http://www.ctrip.com/",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "携程商旅",
            "parentIds": "0/",
            "pId": "10013",
            "id": "318",
            "target": "_blank"
        },
        {
            "hostname": "http://www.bee2c.com/",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "中兴商旅",
            "parentIds": "0/",
            "pId": "10013",
            "id": "317",
            "target": "_blank"
        },
        {
            "hostname": "http://ndss-web.test.bd.dk/ndss-web",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RcSSju5LAAAEDt8kR-w661.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RcS9o_FaAAAD-F5jXaM289.png",
            "icon": "gzyqgl",
            "name": "规则引擎管理",
            "parentIds": "",
            "pId": "0",
            "id": "10025",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "规则引擎管理",
            "parentIds": "0/",
            "pId": "10025",
            "id": "562",
            "target": ""
        },
        {
            "hostname": "http://ndss-web.test.bd.dk/ndss-web/pages/dataIntegration/dataIntegration.jsp\t\t ",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "数据集管理",
            "parentIds": "0/562/",
            "pId": "562",
            "id": "565",
            "target": ""
        },
        {
            "hostname": "http://ndss-web.test.bd.dk/ndss-web/pages/simulationTest/simulationTest.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "仿真测试管理 ",
            "parentIds": "0/562/",
            "pId": "562",
            "id": "1316",
            "target": ""
        },
        {
            "hostname": "http://ndss-web.test.bd.dk/ndss-web/pages/dataSource/ruleConfiguration-base.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "数据源管理",
            "parentIds": "0/562/",
            "pId": "562",
            "id": "564",
            "target": ""
        },
        {
            "hostname": "http://ndss-web.test.bd.dk/ndss-web/pages/sysandrule/systemList.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "业务系统管理",
            "parentIds": "0/562/",
            "pId": "562",
            "id": "566",
            "target": ""
        },
        {
            "hostname": "http://ndss-web.test.bd.dk/ndss-web/pages/linkLibrary/linkLibrary.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "连接库管理",
            "parentIds": "0/562/",
            "pId": "562",
            "id": "563",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5QayPe_pDAAAEEwOrj5I553.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5QayjlozJAAAD-cGe6BI910.png",
            "icon": "cpzx",
            "name": "产品中心",
            "parentIds": "",
            "pId": "0",
            "id": "10026",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcHome/index.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "产品查询",
            "parentIds": "0/",
            "pId": "10026",
            "id": "571",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "产品管理",
            "parentIds": "0/",
            "pId": "10026",
            "id": "598",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcProduct/productUsableRange.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "联合贷管理",
            "parentIds": "0/598/",
            "pId": "598",
            "id": "3243",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcProduct/productSend.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "产品发布",
            "parentIds": "0/598/",
            "pId": "598",
            "id": "600",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcProduct/productList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "产品设计",
            "parentIds": "0/598/",
            "pId": "598",
            "id": "599",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "产品配置",
            "parentIds": "0/",
            "pId": "10026",
            "id": "601",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcModel/productModelList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "产品模型",
            "parentIds": "0/601/",
            "pId": "601",
            "id": "603",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcTemplet/templateList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "产品模板",
            "parentIds": "0/601/",
            "pId": "601",
            "id": "604",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcProductParams/toProductParam.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "产品参数",
            "parentIds": "0/601/",
            "pId": "601",
            "id": "605",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/project/projectList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "项目维护",
            "parentIds": "0/601/",
            "pId": "601",
            "id": "602",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "公共管理",
            "parentIds": "0/",
            "pId": "10026",
            "id": "606",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/insuranceCaculator/insuranceCaculator.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保险计算器",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "1212",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcGPSPlan/gpsPlanList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "GPS方案",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "610",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/upperLimitAccount/upperLimitAccount.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "账户管理费上限管理",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "2261",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/commissionRule/commissionRule.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "佣金规则配置",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "1313",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/approveRules/approveRules-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "审批规则配置",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "829",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/ pdcGPSPrice/gpsPriceList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "GPS价格类型",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "608",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/creditRuleCheckConfig/creditRuleCheckConfig.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "征信必查规则配置",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "1724",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/creditRule/creditRule.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "征信规则配置",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "1312",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/wfptTemplet/wfptTemplet-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "流程模板配置",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "815",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pdcFincItem/fincItemList.do",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "融资项目",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "607",
            "target": ""
        },
        {
            "hostname": "http://pdc-web.test.bd.dk/pdc-web/pages/publicManage/valFloatManage.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "估价上浮管理 ",
            "parentIds": "0/606/",
            "pId": "606",
            "id": "1401",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group2/M00/03/F1/wKibNVr83u-URBnbAAAnx8rPa5A706.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group2/M00/03/F1/wKibNVr83u6Ft_ovAAAnx8rPa5A047.png",
            "icon": "",
            "name": "YxCode",
            "parentIds": "",
            "pId": "0",
            "id": "10273",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "YxCode脚手架工程",
            "parentIds": "0/",
            "pId": "10273",
            "id": "3406",
            "target": ""
        },
        {
            "hostname": "/yxcode-demo/index.html#/workApply",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "渠道审批",
            "parentIds": "0/3406/",
            "pId": "3406",
            "id": "3458",
            "target": ""
        },
        {
            "hostname": "/yxcode-demo/index.html#/information",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "渠道申请",
            "parentIds": "0/3406/",
            "pId": "3406",
            "id": "3457",
            "target": ""
        },
        {
            "hostname": "/yxcode-demo/index.html#/demo",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "YxCodeDemo",
            "parentIds": "0/3406/",
            "pId": "3406",
            "id": "3412",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.32:8272/noaapp/pages/NIM_Web",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "txpt",
            "name": "通讯平台",
            "parentIds": "",
            "pId": "0",
            "id": "10031",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.32:8272/noaapp/pages/NIM_Web/webdemo/im/index.html",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "聊天平台",
            "parentIds": "0/",
            "pId": "10031",
            "id": "806",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "ncallcenter",
            "name": "电销系统重构",
            "parentIds": "",
            "pId": "0",
            "id": "10036",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "公告管理",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1201",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/notice/noticelist.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "公告管理",
            "parentIds": "0/1201/",
            "pId": "1201",
            "id": "1202",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "呼出任务",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1185",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/callouttask/outtask-frame.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "我的任务",
            "parentIds": "0/1185/",
            "pId": "1185",
            "id": "1190",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/workform/workform-out-follow.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "任务跟进",
            "parentIds": "0/1185/",
            "pId": "1185",
            "id": "1187",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/workform/workform-out-queue.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "任务队列",
            "parentIds": "0/1185/",
            "pId": "1185",
            "id": "1186",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "软电话内呼",
            "parentIds": "0/",
            "pId": "10036",
            "id": "2120",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "配置管理",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1192",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/smstemplate/template-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "短信模板",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1198",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/group/group-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "分组管理",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1195",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/suffixConfig/suffix-config-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "分机号配置",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "3280",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/quality/quality-papper-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "质检问卷",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1200",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/gift/gift-list.jsp?cc=1",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "赠品管理",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1197",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/rule/rule-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "规则管理",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1194",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/uipConfig/uip-config-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "UIP配置",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "3279",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/quality/quality-question-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "质检题库",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1199",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/agent/agent-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "用户管理",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1196",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/emailConfig/email-config.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "邮件配置",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "3446",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/org/org-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "部门管理",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1193",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/org/recycle-view.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "回收机制设置",
            "parentIds": "0/1192/",
            "pId": "1192",
            "id": "1205",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "任务管理",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1183",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/workform/workform-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "任务管理",
            "parentIds": "0/1183/",
            "pId": "1183",
            "id": "1184",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "内呼话务统计",
            "parentIds": "0/",
            "pId": "10036",
            "id": "3469",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/teamanalysis/telephone-traffic-in.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "呼入报表",
            "parentIds": "0/3469/",
            "pId": "3469",
            "id": "3475",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/trafficInfo/received-calls.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "已接来电",
            "parentIds": "0/3469/",
            "pId": "3469",
            "id": "3472",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/teamanalysis/telephone-traffic-backcall.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "回电报表",
            "parentIds": "0/3469/",
            "pId": "3469",
            "id": "3474",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/trafficInfo/missed-calls.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "未接来电",
            "parentIds": "0/3469/",
            "pId": "3469",
            "id": "3471",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/trafficInfo/satisfied-count.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "满意度统计",
            "parentIds": "0/3469/",
            "pId": "3469",
            "id": "3473",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/trafficInfo/169-hot-line.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "169热线",
            "parentIds": "0/3469/",
            "pId": "3469",
            "id": "3470",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "质量管理",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1203",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/quality/quality-grade-history-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "电销历史质检",
            "parentIds": "0/1203/",
            "pId": "1203",
            "id": "3344",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/quality/quality-grade-list.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "电销质检",
            "parentIds": "0/1203/",
            "pId": "1203",
            "id": "1204",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "呼入任务",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1188",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/workform/workform-in-demand.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "线索查询及创建",
            "parentIds": "0/1188/",
            "pId": "1188",
            "id": "1189",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "软电话",
            "parentIds": "0/",
            "pId": "10036",
            "id": "1182",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.90:8090/callcenter-web/pages/workform/workform-list3.jsp",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "任务管理-独号",
            "parentIds": "0/",
            "pId": "10036",
            "id": "3133",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RlC91INoAAAERR5KKLo869.png",
            "isParent": "1",
            "defaultIcon": "http://192.168.145.34/group1/M00/04/2A/wKiRIll5RlCU54f5AAAENcCQ5R8412.png",
            "icon": "yxfwpt",
            "name": "营销服务平台",
            "parentIds": "",
            "pId": "0",
            "id": "10032",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "渠道管理",
            "parentIds": "0/",
            "pId": "10032",
            "id": "918",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=channel/index.html#!/channelList",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "已合作渠道",
            "parentIds": "0/918/",
            "pId": "918",
            "id": "919",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "线索分发及回收管理",
            "parentIds": "0/",
            "pId": "10032",
            "id": "904",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=engine/index.html#!/twodistribution",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "二级分发 ",
            "parentIds": "0/904/",
            "pId": "904",
            "id": "907",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=engine/index.html#!/oneDistribution",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "一级分发",
            "parentIds": "0/904/",
            "pId": "904",
            "id": "906",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=engine/index.html#!/threedistributionEngine",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "三级分发",
            "parentIds": "0/904/",
            "pId": "904",
            "id": "908",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=engine/index.html#!/templateManagement",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "模板管理 ",
            "parentIds": "0/904/",
            "pId": "904",
            "id": "905",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/reportManagement",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "报表管理",
            "parentIds": "0/",
            "pId": "10032",
            "id": "2200",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "任务管理",
            "parentIds": "0/",
            "pId": "10032",
            "id": "915",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=managements/index.html#!/management",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "业绩",
            "parentIds": "0/915/",
            "pId": "915",
            "id": "934",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "系统管理",
            "parentIds": "0/",
            "pId": "10032",
            "id": "903",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "线索运维",
            "parentIds": "0/903/",
            "pId": "903",
            "id": "2330",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=organize/index.html#!/organize/list",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "账号管理",
            "parentIds": "0/903/",
            "pId": "903",
            "id": "914",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=organize/index.html#!/organize",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "部门管理",
            "parentIds": "0/903/",
            "pId": "903",
            "id": "913",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "ssp经营性租赁",
            "parentIds": "0/",
            "pId": "10032",
            "id": "2167",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.37/ol-web/static.do?url=reconsitutionclues/index.html#!/applylist",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "申请管理",
            "parentIds": "0/2167/",
            "pId": "2167",
            "id": "2185",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.37/ol-web/static.do?url=gps/index.html#!/regionalManager",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "区域经营费用确认",
            "parentIds": "0/2167/",
            "pId": "2167",
            "id": "2170",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.37/ol-web/static.do?url=reconsitutionclues/index.html#!/",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "线索管理",
            "parentIds": "0/2167/",
            "pId": "2167",
            "id": "2184",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.37/ol-web/static.do?url=gps/index.html#!/paymentConfirmation",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "付款确认列表",
            "parentIds": "0/2167/",
            "pId": "2167",
            "id": "2169",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.37/ol-web/static.do?url=gps/index.html#!/bigRegionalManager",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "大区经理审批列表",
            "parentIds": "0/2167/",
            "pId": "2167",
            "id": "2171",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.37/ol-web/static.do?url=clues/index.html#!/moresearch/cluesall",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "经营性租赁新车贷款",
            "parentIds": "0/2167/",
            "pId": "2167",
            "id": "2168",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "运营模块",
            "parentIds": "0/",
            "pId": "10032",
            "id": "909",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=gps/index.html#!/cardchange",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "GPS卡号修改",
            "parentIds": "0/909/",
            "pId": "909",
            "id": "912",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=original/index.html#!/ticketManagement?doremind=doremind",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "退票管理",
            "parentIds": "0/909/",
            "pId": "909",
            "id": "3177",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=gps/index.html#!/entering/noenter",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "GPS信息录入",
            "parentIds": "0/909/",
            "pId": "909",
            "id": "911",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=original/index.html#!/original",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "原件邮寄",
            "parentIds": "0/909/",
            "pId": "909",
            "id": "916",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=gps/index.html#!/gpslist/tosubmit",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "GPS安装单",
            "parentIds": "0/909/",
            "pId": "909",
            "id": "910",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "线索/申请管理",
            "parentIds": "0/",
            "pId": "10032",
            "id": "901",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/applylist",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "申请管理",
            "parentIds": "0/901/",
            "pId": "901",
            "id": "1806",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/Carreport",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "二手车评估报告管理",
            "parentIds": "0/901/",
            "pId": "901",
            "id": "2416",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "线索管理",
            "parentIds": "0/901/",
            "pId": "901",
            "id": "1805",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=nssp_v2.0/index.html#/detailList/detailsInfo",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "nssp_v2.0",
            "parentIds": "0/901/",
            "pId": "901",
            "id": "2332",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=clues/index.html#!/moresearch/cluesall",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "新车贷款",
            "parentIds": "0/901/",
            "pId": "901",
            "id": "902",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "保险运营",
            "parentIds": "0/",
            "pId": "10032",
            "id": "2408",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/insuranceRear",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保险后置管理",
            "parentIds": "0/2408/",
            "pId": "2408",
            "id": "3242",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/setting_index",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保险流程配置",
            "parentIds": "0/2408/",
            "pId": "2408",
            "id": "2411",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/headquartersReview",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "总部复核配置",
            "parentIds": "0/2408/",
            "pId": "2408",
            "id": "3120",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/approve_index",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保费结算审批",
            "parentIds": "0/2408/",
            "pId": "2408",
            "id": "2410",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/archiving_index",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保费归档",
            "parentIds": "0/2408/",
            "pId": "2408",
            "id": "2412",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/nssp-web/static.do?url=reconsitutionclues/index.html#!/clearing_index",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保费结算",
            "parentIds": "0/2408/",
            "pId": "2408",
            "id": "2409",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "yxfwpt",
            "name": "贷后运营",
            "parentIds": "",
            "pId": "0",
            "id": "10040",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "合同取消",
            "parentIds": "0/",
            "pId": "10040",
            "id": "1966",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/contractCancel/index.html#/capitalCostReceiveList",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "资金确认收款",
            "parentIds": "0/1966/",
            "pId": "1966",
            "id": "1969",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/contractCancel/index.html#/insuranceList",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保险费用确认",
            "parentIds": "0/1966/",
            "pId": "1966",
            "id": "1968",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/contractCancel/index.html#/capitalCostRefundList",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "资金确认退款",
            "parentIds": "0/1966/",
            "pId": "1966",
            "id": "1970",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/contractCancel/index.html#/gpsList",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "gps费用确认",
            "parentIds": "0/1966/",
            "pId": "1966",
            "id": "1967",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "保险运营",
            "parentIds": "0/",
            "pId": "10040",
            "id": "1465",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/insurance/index.html#!/renewalapply",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "续保保单审批",
            "parentIds": "0/1465/",
            "pId": "1465",
            "id": "1606",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/insurance/index.html#!/insurepoliupload",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "首保保单上传",
            "parentIds": "0/1465/",
            "pId": "1465",
            "id": "1579",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/insurance/index.html#!/renewalpoliupload",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "续保保单上传",
            "parentIds": "0/1465/",
            "pId": "1465",
            "id": "1590",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/insurance/index.html#!/insureQuery",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "保险查询",
            "parentIds": "0/1465/",
            "pId": "1465",
            "id": "1467",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/insurance/index.html#!/insurepoli",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "首保保单审批",
            "parentIds": "0/1465/",
            "pId": "1465",
            "id": "1586",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web\t/static.do?url=/insurance/index.html#!/insureapply",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "首保申请",
            "parentIds": "0/1465/",
            "pId": "1465",
            "id": "1466",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/insurance/index.html#!/taskPoolLog",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "任务池管理",
            "parentIds": "0/",
            "pId": "10040",
            "id": "3267",
            "target": ""
        },
        {
            "hostname": "",
            "checkedIcon": "",
            "isParent": "1",
            "defaultIcon": "",
            "icon": "",
            "name": "车务管理",
            "parentIds": "0/",
            "pId": "10040",
            "id": "1359",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/branchContact",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "分公司联系人管理",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "3293",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/mortgageFilingSign",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "标记解除抵押",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "1323",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/mortgageFiling",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "申请抵押备案材料",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "1326",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/mortgageFilingConfirm",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "解除抵押确认",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "1322",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/releaseagency",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "解除抵押(分平台)",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "3423",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/vehicleTranApplication",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "车辆过户",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "1324",
            "target": ""
        },
        {
            "hostname": "http://192.168.145.33/operloan-web/static.do?url=/vehiclework/index.html#!/releaseMortgage",
            "checkedIcon": "",
            "isParent": "0",
            "defaultIcon": "",
            "icon": "",
            "name": "车辆解除抵押",
            "parentIds": "0/1359/",
            "pId": "1359",
            "id": "1321",
            "target": ""
        }]
    return (
      <div className="App">
          <Index navList={navList} />
      </div>
    );
  }
}

export default App;
